server:
    port: 8085
    servlet: 
     context-path: /booking
     
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  
app:
  services:
    listing: "http://localhost:8083/listing"
    profile: "http://localhost:8081/profile"

jwt:
  secretKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  access-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds